/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManagementSystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Sarvendu Pandey
 */
public class AdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    public AdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddStudent = new javax.swing.JButton();
        AddResults = new javax.swing.JButton();
        ListStudents = new javax.swing.JButton();
        UpdateStudents = new javax.swing.JButton();
        ListStudentsResults = new javax.swing.JButton();
        Lagout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/schoolPic1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 560));
        setMinimumSize(new java.awt.Dimension(700, 560));
        setPreferredSize(new java.awt.Dimension(700, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/icons8-student.png"))); // NOI18N
        AddStudent.setText("Add Student");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 60));

        AddResults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/icons8-grade-24.png"))); // NOI18N
        AddResults.setText("add Result");
        AddResults.setMaximumSize(new java.awt.Dimension(182, 70));
        AddResults.setMinimumSize(new java.awt.Dimension(182, 70));
        AddResults.setPreferredSize(new java.awt.Dimension(182, 70));
        AddResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddResultsActionPerformed(evt);
            }
        });
        getContentPane().add(AddResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 60));

        ListStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ListStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/icons8-checklist-30.png"))); // NOI18N
        ListStudents.setText("List Students");
        ListStudents.setMaximumSize(new java.awt.Dimension(182, 70));
        ListStudents.setMinimumSize(new java.awt.Dimension(182, 70));
        ListStudents.setPreferredSize(new java.awt.Dimension(182, 70));
        ListStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(ListStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, 60));

        UpdateStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/icons8-edit student.png"))); // NOI18N
        UpdateStudents.setText("Update Students");
        UpdateStudents.setMaximumSize(new java.awt.Dimension(182, 70));
        UpdateStudents.setMinimumSize(new java.awt.Dimension(182, 70));
        UpdateStudents.setPreferredSize(new java.awt.Dimension(182, 70));
        UpdateStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 190, 60));

        ListStudentsResults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ListStudentsResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/icons8-checklist-30.png"))); // NOI18N
        ListStudentsResults.setText("List Students Results");
        ListStudentsResults.setMaximumSize(new java.awt.Dimension(182, 70));
        ListStudentsResults.setMinimumSize(new java.awt.Dimension(182, 70));
        ListStudentsResults.setPreferredSize(new java.awt.Dimension(182, 70));
        ListStudentsResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListStudentsResultsActionPerformed(evt);
            }
        });
        getContentPane().add(ListStudentsResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 190, 60));

        Lagout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lagout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/icons8-logout-50.png"))); // NOI18N
        Lagout.setText("Lagout");
        Lagout.setMaximumSize(new java.awt.Dimension(182, 70));
        Lagout.setMinimumSize(new java.awt.Dimension(182, 70));
        Lagout.setPreferredSize(new java.awt.Dimension(182, 70));
        Lagout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LagoutActionPerformed(evt);
            }
        });
        getContentPane().add(Lagout, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 180, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/schoolPic2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddResultsActionPerformed
        // TODO add your handling code here:
        AddResults frame = new AddResults();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);

    }//GEN-LAST:event_AddResultsActionPerformed

    private void ListStudentsResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListStudentsResultsActionPerformed
        // TODO add your handling code here:
        ListStudentResult frame = new ListStudentResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_ListStudentsResultsActionPerformed

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        // TODO add your handling code here:
           AddStudent frame = new AddStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);

    }//GEN-LAST:event_AddStudentActionPerformed

    private void UpdateStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStudentsActionPerformed
        // TODO add your handling code here:
        UpdateStudent frame = new UpdateStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateStudentsActionPerformed

    private void LagoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LagoutActionPerformed
        // TODO add your handling code here:
          int flag = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit", "Submit", JOptionPane.YES_NO_OPTION);
        if(flag == 0){
            setVisible(false); 
   
         Home frame = new Home();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }

    }//GEN-LAST:event_LagoutActionPerformed

    private void ListStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListStudentsActionPerformed
        // TODO add your handling code here:
        ListStudents frame = new ListStudents();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);

    }//GEN-LAST:event_ListStudentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddResults;
    private javax.swing.JButton AddStudent;
    private javax.swing.JButton Lagout;
    private javax.swing.JButton ListStudents;
    private javax.swing.JButton ListStudentsResults;
    private javax.swing.JButton UpdateStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
